### ISSUE TITLE
TypeError with default = None

### ISSUE THREAD

**Issue by ornemarioni** [quatrope/uttrs#1]
This test fail:
``` python
    import uttr
    import attr
    import astropy.units as u

    @attr.s()
    class Galaxy:
        x = uttr.ib(unit=u.kpc)
        y = uttr.ib(default = 0 ,unit=u.kpc)
        z = uttr.ib(default = None ,unit=u.Msun)

    g = Galaxy(x=np.array([5,2])*u.km)
```

**Comment by leliel12** [comment]
Please:

- Explain the error
- design the test with the correct `test_` name
- Remove all the non-failing lines

**Comment by leliel12** [comment]
This test was implemented

https://github.com/quatrope/uttrs/blob/c5eee34dd0a8d1b69b0f5486c17b08cce0644023/tests/test_issues.py#L32-L42
