### ISSUE TITLE
create _arr accessor method automagically

### ISSUE THREAD

**Issue by martinberoiz** [quatrope/uttrs#4]
Suggestion:

I propose that instead of the user having to add the accessor attribute `_arr` to the class, the property is automatically added to the class scope on creation.

**Comment by leliel12** [comment]
uttrs is just a simple extension of attrs. Essentially it provides two functions that generate preconfigured attributes. But at no time will it interfere with the original operation of `@ attr.s`. So I don't have access to the class where these attributes are added. To achieve this objective it would be necessary to implement #5
